CREATE TABLE public.tvs
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand VARCHAR(255)                            NOT NULL,
    model VARCHAR(255)                            NOT NULL,
    screen VARCHAR(255)                           NOT NULL,
    CONSTRAINT pk_tvs PRIMARY KEY (id)
);