services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    command:
      - java -jar app.jar

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=homework23
    ports:
      - "5440:5432"  # так нужно было
    volumes:
      - postgres-data-homework23:/var/lib/postgresql/data/

volumes:
  postgres-data-homework23: