CREATE TABLE addresses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    locality   VARCHAR(255)                            NOT NULL,
    street     VARCHAR(255)                            NOT NULL,
    house      VARCHAR(255)                            NOT NULL,
    porch      VARCHAR(255),
    floor      VARCHAR(255),
    apartment  VARCHAR(255)                            NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    pizza_id   BIGINT                                  NOT NULL,
    address_id BIGINT                                  NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE pizzas
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_pizzas PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    is_deleted   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE addresses
    ADD CONSTRAINT FK_ADDRESSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_PIZZA FOREIGN KEY (pizza_id) REFERENCES pizzas (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);